#!/bin/sh

# DS="/sdcard/backups/apps/DroidScript_1.15.apk"
#DS="/sdcard/backups/apps/DroidScript_135a9.apk"
DS="/sdcard/backups/apps/"

# Examples for specifying DroidScript to use:
#   Latest: DS="/sdcard/backups/apps/"
#   Target: DS="/sdcard/backups/apps/DroidScript_1.15.apk" 

export DS
while [ true ]; do
    echo "Starting ar2dscript server..."
    ./serve/main.js || {
	echo "Terminated with error code: $?"
	sleep 30
	grep -q '"debug":true' serve/config.json && { sleep 300; } || reboot # For deployed devices
    } 
    sleep 1
done
